name: Container Security Scan (Trivy)

# Déclencheurs : push sur main + lancement manuel
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t security-lab:latest .

      # 3️⃣ Run Trivy Scanner
      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true               # ← continue même si vulnérabilités
        with:
          image-ref: "security-lab:latest"
          format: "json"
          output: "scan-results/trivy-report.json"
          exit-code: "0"                     # ← ne fait pas échouer le job
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"

      # 4️⃣ Convert JSON report → HTML (optionnel, plus lisible)
      - name: Generate HTML Report
        run: |
          mkdir -p scan-results
          docker run --rm \
            -v $PWD/scan-results:/src \
            python:3.11-slim \
            sh -c "pip install trivy-to-html && trivy-to-html -i /src/trivy-report.json -o /src/trivy-report.html"

      # 5️⃣ Upload Artifacts (toujours exécuté)
      - name: Upload Artifacts
        if: always()                        # ← permet d'uploader même si Trivy a trouvé des vulnérabilités
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: scan-results/
